config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'update'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new

  end

  def create
    @todo = Todo.new(post_params)
    @todo.completed = false
    @todo.save
    redirect_to todos_path

  end

  def show
    @todo = Todo.find(params[:id])

  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(post_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path

  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_list_path

  end

  def list
    @todos = Todo.all

  end

  private
  def post_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'todos/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <%= f.label :description, "Descripción" %>
  <%= f.text_field :description %>

  <!-- <%= f.label :completed, "Completado" %>
  <%= f.text_area :completed %> -->

  <%= f.submit "Aceptar" %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li >
        <%= link_to "Index", todos_path, class: 'btn btn-light' %>
      </li>
      <li >
        <%= link_to "List", todos_list_path, class: 'btn btn-light' %>
      </li>
      <li >
        <%= link_to "Nuevo", todos_new_path, class: 'btn btn-light' %>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<!-- <h1><%= link_to "Crear tarea", todos_new_path %></h1> -->

<% @todos.each do |todo| %>
<div style="border-style: dotted;">
  <h2> <%=todo.description%>  </h2>
  <!-- <p> <%= todo.completed %> </p> -->
  <%= link_to "Mostrar", todo, class: 'btn btn-primary'  %>
  <%= link_to "Editar", update_path(todo), class: 'btn btn-warning'  %>
  <%= link_to "Borrar", todo, method: :delete, class: 'btn btn-danger'  %>
</div>

<% end %>

app/views/todos/list.html.erb
<div class="row">
  <div class="col-lg-6">
    <% @todos.each do |todo| %>
      <% if todo.completed == false %>
      <div style="border-style: dotted;">
        <h2> <%=todo.description%> <%= link_to "Completar", complete_path(todo), class: 'btn btn-info' %> </h2>
        <!-- <p> <%= todo.completed %> </p> -->
      </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-lg-6">
    <% @todos.each do |todo| %>
      <% if todo.completed == true %>
      <div style="border-style: dotted;">
        <h2> <%=todo.description%></h2>
        <!-- <p> <%= todo.completed %> </p> -->
      </div>        
      <% end %>
    <% end %>
  </div>
</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h2><%= @todo.description %></h2>
<!-- <h2><%= @todo.completed %></h2> -->
<%= link_to "Volver", todos_path, class: 'btn btn-secondary' %>